name: simple_notes
description: "simple_notes"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1
  auto_route: ^7.8.4
  flutter_screenutil: ^5.9.0
  uuid: ^4.2.2
  flutter_staggered_animations: ^1.1.1
  flutter_local_notifications: ^16.3.0
  dio: ^5.4.0
  timezone: ^0.9.2
  flutter_timezone: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.9
  isar_generator: ^3.1.0+1
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true